CREATE DATABASE kino4tigr1; 

CREATE TABLE FILMY (
    ID int  AUTO_INCREMENT NOT NULL PRIMARY KEY,
    TYTUL varchar (255) NOT NULL,
    REZYSER varchar (255) NOT NULL,
    CZAS_TRWANIA_MIN int NOT NULL
);

CREATE TABLE RODZAJ_FILMU (
    ID int  AUTO_INCREMENT NOT NULL PRIMARY KEY,
    NAZWA varchar (255)
);

CREATE TABLE FILMY_RODZAJ (
    ID int  AUTO_INCREMENT NOT NULL PRIMARY KEY,
    FILMY_ID int NOT NULL,
    RODZAJ_ID int NOT NULL,
    
    CONSTRAINT `filmy_fk` FOREIGN KEY (`FILMY_ID`)
     REFERENCES FILMY(`ID`),
    
    CONSTRAINT `rodzaj_fk` FOREIGN KEY (`RODZAJ_ID`)
    	REFERENCES RODZAJ_FILMU(`ID`) 
);

CREATE TABLE SALE (
    ID int  AUTO_INCREMENT NOT NULL PRIMARY KEY,
    ILOSC_MIEJSC INT NOT NULL
);

CREATE TABLE SEANSE (
    ID int  AUTO_INCREMENT NOT NULL PRIMARY KEY,
    TERMIN DATETIME NOT NULL,
    SALA_ID Int NOT NULL,
    FILM_ID int NOT NULL,
    LICZBA_WOLNYCH_MIEJSC int NOT NULL,
    
    CONSTRAINT `sale_fk` FOREIGN KEY (`SALA_ID`)
    	REFERENCES SALE(`ID`),
    
    CONSTRAINT `film_fk` FOREIGN KEY (`FILM_ID`)
    	REFERENCES FILMY(`ID`)  
);

CREATE TABLE KLIENCI (
    ID int  AUTO_INCREMENT NOT NULL PRIMARY KEY,
    IMIE varchar (255) NOT NULL,
    NAZWISKO varchar (255) NOT NULL,
    MAIL varchar (255) NOT NULL
);

CREATE TABLE SPRZEDAWCY (
    ID int  AUTO_INCREMENT NOT NULL PRIMARY KEY,
    IMIE varchar (255) NOT NULL,
    NAZWISKO varchar (255) NOT NULL
);

CREATE TABLE BILETY (
    ID int  AUTO_INCREMENT NOT NULL PRIMARY KEY,
    SEANS_ID int NOT NULL,
    SPRZEDAWCA_ID int NOT NULL,
    KLIENT_ID int NOT NULL,
    CENA int NOT NULL,
    
    CONSTRAINT `seans_fk` FOREIGN KEY (`SEANS_ID`)
    	REFERENCES SEANSE(`ID`),
    
    CONSTRAINT `sprzedawca_fk` FOREIGN KEY (`SPRZEDAWCA_ID`)
    	REFERENCES SPRZEDAWCY(`ID`),

    CONSTRAINT `klient_fk` FOREIGN KEY (`KLIENT_ID`)
    	REFERENCES KLIENCI(`ID`)   
);


