CREATE DATABASE kino4tigr1; 

CREATE TABLE FILMY (
    ID bigint AUTO_INCREMENT PRIMARY KEY NOT NULL,
    TYTUL varchar (255) NOT NULL,
    REZYSER varchar (255) NOT NULL,
    CZAS_TRWANIA_MIN bigint NOT NULL
);

CREATE TABLE RODZAJ_FILMU (
    ID bigint AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NAZWA varchar (255)
);

CREATE TABLE FILMY_RODZAJ (
    ID bigint AUTO_INCREMENT PRIMARY KEY NOT NULL,
    FILMY_ID bigint NOT NULL,
    RODZAJ_ID bigint NOT NULL,
    
    CONSTRAINT `filmy_fk` FOREIGN KEY (`FILMY_ID`)
     REFERENCES FILMY(`ID`),
    
    CONSTRAINT `rodzaj_fk` FOREIGN KEY (`RODZAJ_ID`)
    	REFERENCES RODZAJ_FILMU(`ID`) 
);

CREATE TABLE SALE (
    ID bigint AUTO_INCREMENT PRIMARY KEY NOT NULL,
    ILOSC_MIEJSC BIGINT NOT NULL
);

CREATE TABLE SEANSE (
    ID bigint AUTO_INCREMENT PRIMARY KEY NOT NULL,
    TERMIN DATETIME NOT NULL,
    SALA_ID bigint NOT NULL,
    FILM_ID bigint NOT NULL,
    LICZBA_WOLNYCH_MIEJSC BIGINT NOT NULL,
    
    CONSTRAINT `sale_fk` FOREIGN KEY (`SALA_ID`)
    	REFERENCES SALE(`ID`),
    
    CONSTRAINT `film_fk` FOREIGN KEY (`FILM_ID`)
    	REFERENCES FILMY(`ID`)  
);

CREATE TABLE KLIENCI (
    ID bigint AUTO_INCREMENT PRIMARY KEY NOT NULL,
    IMIE varchar (255) NOT NULL,
    NAZWISKO varchar (255) NOT NULL,
    MAIL varchar (255) NOT NULL
);

CREATE TABLE SPRZEDAWCY (
    ID bigint AUTO_INCREMENT PRIMARY KEY NOT NULL,
    IMIE varchar (255) NOT NULL,
    NAZWISKO varchar (255) NOT NULL
);

CREATE TABLE BILETY (
    ID bigint AUTO_INCREMENT PRIMARY KEY NOT NULL,
    SEANS_ID bigint NOT NULL,
    SPRZEDAWCA_ID bigint NOT NULL,
    KLIENT_ID bigint NOT NULL,
    CENA bigint NOT NULL,
    
    CONSTRAINT `seans_fk` FOREIGN KEY (`SEANS_ID`)
    	REFERENCES SEANSE(`ID`),
    
    CONSTRAINT `sprzedawca_fk` FOREIGN KEY (`SPRZEDAWCA_ID`)
    	REFERENCES SPRZEDAWCY(`ID`),

    CONSTRAINT `klient_fk` FOREIGN KEY (`KLIENT_ID`)
    	REFERENCES KLIENCI(`ID`)   
);


INSERT INTO `SPRZEDAWCY` (`ID`, `IMIE`, `NAZWISKO`) VALUES 
(NULL, 'Jan', 'Bogucki'),
(NULL,'Michał', 'Więcek'),
(NULL,'Bożena', 'Michalska'),
(NULL,'Krystyna', 'Piętkiewicz'),
(NULL,'Maciej', 'Stasiak');

INSERT INTO `SALE` (`ID`, `ILOSC_MIEJSC`) VALUES 
(NULL, 200),
(NULL, 120),
(NULL, 300),
(NULL, 145),
(NULL, 50);

INSERT INTO `KLIENCI` (`ID`, `IMIE`, `NAZWISKO`, `MAIL`) VALUES 
(NULL, `Janusz`, `Męczykowski`, `janusz.meczykowski@wp.pl`),
(NULL, `Jarosław`, `Kuc`, `jarekcuk@wp.pl`),
(NULL, `Andrzej`),
(NULL, 145),
(NULL, 50);